// Quiz logic. Question data lives in questions.js (auto-generated by backend.py).
// The `questions` global is expected to be defined by questions.js, loaded before this file.


// ---------------------------------------------------------------------------
// API routing
// Talks to server.py. By default API requests use same-origin when hosted
// (e.g. Render), and fallback to http://127.0.0.1:5001 for local file:// use.
// Override by setting window.QUIZ_API_BASE before this script.
// ---------------------------------------------------------------------------
const QUIZ_API_DEFAULT_HOSTS = ['127.0.0.1:5001', 'localhost:5001'];
const QUIZ_API_DEFAULT_BASE = 'http://127.0.0.1:5001';

function quizApiUrl(path) {
    let base = (typeof window !== 'undefined') ? window.QUIZ_API_BASE : undefined;
    if (typeof base !== 'string') {
        const onFlask = typeof window !== 'undefined'
            && QUIZ_API_DEFAULT_HOSTS.indexOf(window.location.host) !== -1;
        if (onFlask) {
            base = '';
        } else if (typeof window !== 'undefined' && window.location.protocol === 'file:') {
            base = QUIZ_API_DEFAULT_BASE;
        } else if (typeof window !== 'undefined'
            && (window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1')) {
            base = window.location.protocol + '//' + window.location.hostname + ':5001';
        } else {
            base = window.location.origin;
        }
    }
    return base.replace(/\/$/, '') + path;
}


// ===========================================================================
// QSetStore — PostgreSQL-backed persistence for the signed-in user.
//
// The store keeps an in-memory cache hydrated from the API on sign-in so the
// rest of the app can keep calling `QSetStore.list()` / `.get(id)` etc.
// synchronously. Mutations write through to the API in the background; the
// cache is the read source of truth.
//
// Endpoints (all session-cookie authenticated, scoped server-side by user id):
//   GET    /api/sets             → list user's set summaries
//   GET    /api/sets/<id>        → full record
//   POST   /api/sets             → upsert
//   DELETE /api/sets/<id>        → remove
//   POST   /api/sets/<id>/stats  → record a practice score
//   GET/PUT /api/active-set      → which set drives the quiz
// ===========================================================================
const QSetStore = (function () {
    const SCHEMA_VERSION = 1;

    // In-memory cache. Hydrated on sign-in via QSetStore.bootstrap().
    const cache = {
        summaries: [],          // [{ id, title, ... }]
        fullRecords: new Map(), // id → full record (lazy-loaded)
        activeId: null,
        ready: false,
    };

    function fetchJSON(url, opts) {
        const o = Object.assign({ credentials: 'include' }, opts || {});
        if (o.body && !(o.body instanceof FormData)) {
            o.headers = Object.assign({ 'Content-Type': 'application/json' }, o.headers || {});
        }
        return fetch(quizApiUrl(url), o).then(async (r) => {
            const text = await r.text();
            let data = null;
            try { data = text ? JSON.parse(text) : null; } catch (_) { /* non-JSON */ }
            return { ok: r.ok, status: r.status, data, text };
        });
    }

    function newId() {
        // Server can also issue an id; this is for clients that need one upfront.
        return 'qs_' + Date.now().toString(36) + '_' + Math.random().toString(36).slice(2, 8);
    }

    async function bootstrap() {
        const [setsRes, activeRes] = await Promise.all([
            fetchJSON('/api/sets'),
            fetchJSON('/api/active-set'),
        ]);
        if (setsRes.ok && setsRes.data && Array.isArray(setsRes.data.sets)) {
            cache.summaries = setsRes.data.sets;
        } else {
            cache.summaries = [];
        }
        if (activeRes.ok && activeRes.data) {
            cache.activeId = activeRes.data.activeId || null;
        } else {
            cache.activeId = null;
        }
        cache.fullRecords.clear();
        cache.ready = true;
    }

    function reset() {
        cache.summaries = [];
        cache.fullRecords.clear();
        cache.activeId = null;
        cache.ready = false;
    }

    function list() {
        return cache.summaries.slice();
    }

    function get(id) {
        if (!id) return null;
        // Synchronous reads come from cache; full records get lazy-loaded
        // asynchronously by `loadFull` (used in hydration) — see Cert.js init.
        return cache.fullRecords.get(id) || null;
    }

    async function loadFull(id) {
        if (!id) return null;
        if (cache.fullRecords.has(id)) return cache.fullRecords.get(id);
        const res = await fetchJSON('/api/sets/' + encodeURIComponent(id));
        if (!res.ok || !res.data || !res.data.set) return null;
        cache.fullRecords.set(id, res.data.set);
        return res.data.set;
    }

    function _upsertSummaryFromRecord(record) {
        const summary = {
            id: record.id,
            title: record.title,
            createdAt: record.createdAt,
            updatedAt: record.updatedAt,
            questionCount: record.questionCount,
            sourceFilename: (record.source && record.source.filename) || null,
            lastPlayedAt: (record.stats && record.stats.lastPlayedAt) || null,
            bestScore: (record.stats && record.stats.bestScore != null) ? record.stats.bestScore : null,
        };
        const i = cache.summaries.findIndex(s => s.id === record.id);
        if (i >= 0) cache.summaries[i] = summary;
        else cache.summaries.unshift(summary);
        cache.fullRecords.set(record.id, record);
    }

    function save(record) {
        // Synchronous-looking API: optimistically update cache, then sync the API.
        if (!record || typeof record !== 'object') return null;
        record.schemaVersion = record.schemaVersion || SCHEMA_VERSION;
        record.id = record.id || newId();
        record.createdAt = record.createdAt || new Date().toISOString();
        record.updatedAt = new Date().toISOString();
        record.questions = Array.isArray(record.questions) ? record.questions : [];
        record.questionCount = record.questions.length;
        record.stats = record.stats || { sessionsRun: 0, lastPlayedAt: null, bestScore: null, averageScore: null };

        _upsertSummaryFromRecord(record);

        fetchJSON('/api/sets', {
            method: 'POST',
            body: JSON.stringify({
                id: record.id,
                title: record.title,
                source: record.source || {},
                questions: record.questions,
                stats: record.stats,
            }),
        }).then((res) => {
            if (!res.ok) console.warn('[QSetStore] save failed:', res.status, res.data && res.data.error);
            else if (res.data && res.data.set) {
                // Re-sync cache with server-canonical record (updates timestamps).
                _upsertSummaryFromRecord(res.data.set);
            }
        }).catch((e) => console.warn('[QSetStore] save network error:', e));

        return record;
    }

    function del(id) {
        if (!id) return;
        cache.summaries = cache.summaries.filter(s => s.id !== id);
        cache.fullRecords.delete(id);
        if (cache.activeId === id) cache.activeId = null;
        fetchJSON('/api/sets/' + encodeURIComponent(id), { method: 'DELETE' })
            .catch((e) => console.warn('[QSetStore] delete network error:', e));
    }

    function getActiveId() {
        return cache.activeId || null;
    }
    function setActiveId(id) {
        cache.activeId = id || null;
        fetchJSON('/api/active-set', {
            method: 'PUT',
            body: JSON.stringify({ activeId: id || null }),
        }).catch((e) => console.warn('[QSetStore] setActive network error:', e));
    }

    function updateStats(id, finalScorePct) {
        // Optimistic local update for snappy UI; server is the source of truth.
        const record = cache.fullRecords.get(id);
        if (record && record.stats) {
            const s = record.stats;
            const prevAvg = s.averageScore;
            s.sessionsRun = (s.sessionsRun || 0) + 1;
            s.lastPlayedAt = new Date().toISOString();
            s.bestScore = (s.bestScore == null) ? finalScorePct : Math.max(s.bestScore, finalScorePct);
            s.averageScore = (prevAvg == null)
                ? finalScorePct
                : Math.round(((prevAvg * (s.sessionsRun - 1)) + finalScorePct) / s.sessionsRun);
            _upsertSummaryFromRecord(record);
        }
        fetchJSON('/api/sets/' + encodeURIComponent(id) + '/stats', {
            method: 'POST',
            body: JSON.stringify({ score: finalScorePct }),
        }).catch((e) => console.warn('[QSetStore] stats network error:', e));
    }

    // pendingSave is no longer needed (server saves directly), but the methods
    // remain as no-ops so any older callers keep working without errors.
    function getPendingSave() { return null; }
    function setPendingSave() { /* no-op */ }
    function clearPendingSave() { /* no-op */ }

    return {
        SCHEMA_VERSION,
        newId, list, get, save, loadFull,
        delete: del,
        getActiveId, setActiveId,
        getPendingSave, setPendingSave, clearPendingSave,
        updateStats,
        bootstrap, reset,
        _cache: cache,
    };
})();


// ===========================================================================
// Auth flow — overlay, sign in/up, sign out.
// ===========================================================================
let currentUser = null;
let authMode = 'signin'; // 'signin' | 'signup'

function isGenerationLimitReached() {
    const usage = currentUser && currentUser.usage;
    if (!usage) return false;
    const used = Number(usage.generationsUsed || 0);
    const limit = Number(usage.generationsLimit || 0);
    return limit > 0 && used >= limit;
}

function usageBadgeText() {
    const usage = currentUser && currentUser.usage;
    if (!usage) return '';
    const tier = (currentUser.planTier || usage.planTier || 'free').toUpperCase();
    const used = Number(usage.generationsUsed || 0);
    const limit = Number(usage.generationsLimit || 0);
    return tier + ' ' + used + '/' + limit + ' generations';
}

function _authFetch(url, opts) {
    const o = Object.assign({ credentials: 'include' }, opts || {});
    if (o.body && !(o.body instanceof FormData)) {
        o.headers = Object.assign({ 'Content-Type': 'application/json' }, o.headers || {});
    }
    return fetch(quizApiUrl(url), o).then(async (r) => {
        const text = await r.text();
        let data = null;
        try { data = text ? JSON.parse(text) : null; } catch (_) {}
        return { ok: r.ok, status: r.status, data };
    });
}

function setAuthMode(mode) {
    authMode = (mode === 'signup') ? 'signup' : 'signin';
    const tabIn = document.getElementById('authTabSignIn');
    const tabUp = document.getElementById('authTabSignUp');
    const emailField = document.getElementById('authEmailField');
    const submitBtn = document.getElementById('authSubmitBtn');
    const title = document.getElementById('authTitle');
    const subtitle = document.getElementById('authSubtitle');
    const passwordInput = document.getElementById('authPassword');

    if (tabIn && tabUp) {
        tabIn.classList.toggle('auth-tab--active', authMode === 'signin');
        tabUp.classList.toggle('auth-tab--active', authMode === 'signup');
        tabIn.setAttribute('aria-selected', authMode === 'signin' ? 'true' : 'false');
        tabUp.setAttribute('aria-selected', authMode === 'signup' ? 'true' : 'false');
    }
    if (emailField) emailField.style.display = authMode === 'signup' ? 'flex' : 'none';
    if (submitBtn) submitBtn.textContent = authMode === 'signup' ? 'Create account' : 'Sign in';
    if (title) title.textContent = authMode === 'signup' ? 'Create your account' : 'Sign in to continue';
    if (subtitle) subtitle.textContent = authMode === 'signup'
        ? 'Your question sets and history will be stored under your account.'
        : 'Your question sets and history stay with your account.';
    if (passwordInput) passwordInput.setAttribute('autocomplete', authMode === 'signup' ? 'new-password' : 'current-password');
    setAuthStatus('', '');
}

function setAuthStatus(text, kind) {
    const el = document.getElementById('authStatus');
    if (!el) return;
    if (!text) {
        el.style.display = 'none';
        el.textContent = '';
        el.className = 'upload-status';
        return;
    }
    el.textContent = text;
    el.className = 'upload-status ' + (kind || '');
    el.style.display = 'block';
}

async function submitAuth() {
    const username = (document.getElementById('authUsername').value || '').trim();
    const password = document.getElementById('authPassword').value || '';
    const email = (document.getElementById('authEmail').value || '').trim();
    const submitBtn = document.getElementById('authSubmitBtn');

    if (!username || !password) {
        setAuthStatus('Username and password are required.', 'error');
        return;
    }

    if (submitBtn) submitBtn.disabled = true;
    setAuthStatus(authMode === 'signup' ? 'Creating your account…' : 'Signing in…', 'loading');

    const url = authMode === 'signup' ? '/api/auth/register' : '/api/auth/login';
    const body = authMode === 'signup' ? { username, password, email } : { username, password };
    const res = await _authFetch(url, { method: 'POST', body: JSON.stringify(body) });

    if (!res.ok || !res.data || !res.data.ok) {
        const msg = (res.data && res.data.error) || ('Failed (HTTP ' + res.status + ')');
        setAuthStatus(msg, 'error');
        if (submitBtn) submitBtn.disabled = false;
        return;
    }

    currentUser = res.data.user;
    setAuthStatus('Welcome, ' + currentUser.username + '!', 'success');
    if (submitBtn) submitBtn.disabled = false;
    await onSignedIn();
}

async function signOut() {
    await _authFetch('/api/auth/logout', { method: 'POST' });
    currentUser = null;
    QSetStore.reset();
    // Reset the in-memory quiz state so nothing leaks into the next user.
    try { localStorage.removeItem('examSessionData'); } catch (_) {}
    // Clean reload puts us back at the auth overlay, with a fresh page.
    window.location.reload();
}

async function checkAuthOnLoad() {
    const res = await _authFetch('/api/auth/me');
    if (res.ok && res.data && res.data.ok && res.data.user) {
        currentUser = res.data.user;
        await onSignedIn();
    } else {
        showAuthOverlay();
    }
}

function showAuthOverlay() {
    const overlay = document.getElementById('authOverlay');
    if (overlay) overlay.style.display = 'flex';
    const pill = document.getElementById('userPill');
    if (pill) pill.style.display = 'none';
    const dashboard = document.getElementById('dashboard');
    if (dashboard) dashboard.style.display = 'none';
}

function hideAuthOverlay() {
    const overlay = document.getElementById('authOverlay');
    if (overlay) overlay.style.display = 'none';
    const dashboard = document.getElementById('dashboard');
    if (dashboard) dashboard.style.display = 'block';
}

function paintUserPill() {
    const pill = document.getElementById('userPill');
    const name = document.getElementById('userPillName');
    const usage = document.getElementById('userPlanUsage');
    if (pill && currentUser) {
        pill.style.display = 'inline-flex';
        if (name) name.textContent = currentUser.username;
        if (usage) {
            const txt = usageBadgeText();
            usage.style.display = txt ? 'inline-flex' : 'none';
            usage.textContent = txt;
        }
    }
}

async function onSignedIn() {
    paintUserPill();
    hideAuthOverlay();

    // Pull this user's saved sets + active set + history from the server
    // before hydrating the quiz, so nothing from the previous user leaks through.
    try {
        await Promise.all([
            QSetStore.bootstrap(),
            bootstrapSessionHistory(),
        ]);
    } catch (e) {
        console.warn('[auth] bootstrap failed:', e);
    }

    // If there's an active set, fetch its full record + swap into `questions`.
    const activeId = QSetStore.getActiveId();
    if (activeId) {
        try {
            const full = await QSetStore.loadFull(activeId);
            if (full && Array.isArray(full.questions) && full.questions.length) {
                replaceLoadedQuestions(full.questions);
            }
        } catch (e) {
            console.warn('[auth] active set hydrate failed:', e);
        }
    }

    // Refresh dashboard widgets that read from server-cached data.
    try { renderQuestionSets(); } catch (_) {}
    try { renderSessionHistory(); } catch (_) {}
}


// Global variables
let selectedTrainingTime = 60; // Default time
let isTimeSet = false;
let currentQuestion = 0;
let userAnswers = {};
let timeLeft = 3600;
let timerInterval;
let isTrainingMode = false;
let isUnlimitedTime = false;
let sessionActive = false;
let selectedMode = null; // 'exam' | 'training' | null

// ---------------------------------------------------------------------------
// Two-step mode selection: pick a mode card, then click Start.
// ---------------------------------------------------------------------------
function selectMode(mode) {
    if (mode !== 'exam' && mode !== 'training') return;
    selectedMode = mode;

    const examCard = document.getElementById('examModeCard');
    const trainingCard = document.getElementById('startTrainingBtn'); // legacy id kept for backwards compat
    if (examCard) {
        examCard.classList.toggle('mode-card--selected', mode === 'exam');
        examCard.setAttribute('aria-checked', mode === 'exam' ? 'true' : 'false');
    }
    if (trainingCard) {
        trainingCard.classList.toggle('mode-card--selected', mode === 'training');
        trainingCard.setAttribute('aria-checked', mode === 'training' ? 'true' : 'false');
    }

    const trainingOptions = document.getElementById('trainingOptions');
    if (trainingOptions) {
        trainingOptions.style.display = mode === 'training' ? 'block' : 'none';
    }

    // When Training is picked, seed isTimeSet from the current input so Start works immediately.
    if (mode === 'training') {
        const input = document.getElementById('timeLimit');
        const minutes = parseInt(input && input.value, 10);
        selectedTrainingTime = (Number.isFinite(minutes) && minutes > 0) ? minutes : 60;
        isTimeSet = true;
    }

    const startBtn = document.getElementById('startSelectedBtn');
    const startLabel = document.getElementById('startSelectedLabel');
    if (startBtn) {
        const wasHidden = startBtn.style.display === 'none' || !startBtn.style.display;
        startBtn.style.display = 'inline-flex';
        startBtn.classList.toggle('btn--primary', mode === 'exam');
        startBtn.classList.toggle('btn--accent', mode === 'training');
        // Retrigger reveal animation only on first reveal, not on every mode switch.
        if (wasHidden) {
            startBtn.classList.remove('start-selected-btn--in');
            // Force reflow so the animation restarts cleanly.
            // eslint-disable-next-line no-unused-expressions
            void startBtn.offsetWidth;
            startBtn.classList.add('start-selected-btn--in');
        }
    }
    if (startLabel) {
        startLabel.textContent = mode === 'exam' ? 'Start Exam' : 'Start Training';
    }
}

function clearModeSelection() {
    selectedMode = null;
    const examCard = document.getElementById('examModeCard');
    const trainingCard = document.getElementById('startTrainingBtn');
    if (examCard) {
        examCard.classList.remove('mode-card--selected');
        examCard.setAttribute('aria-checked', 'false');
    }
    if (trainingCard) {
        trainingCard.classList.remove('mode-card--selected');
        trainingCard.setAttribute('aria-checked', 'false');
    }
    const trainingOptions = document.getElementById('trainingOptions');
    if (trainingOptions) trainingOptions.style.display = 'none';
    const startBtn = document.getElementById('startSelectedBtn');
    if (startBtn) {
        startBtn.style.display = 'none';
        startBtn.classList.remove('start-selected-btn--in');
    }
}

function startSelectedMode() {
    if (selectedMode === 'exam') {
        startExamMode();
    } else if (selectedMode === 'training') {
        beginTraining();
    }
}

// Kept for backwards compatibility — any old caller now just selects Training.
function showTrainingOptions() {
    selectMode('training');
}

function startExamMode() {
    isTrainingMode = false;
    timeLeft = 7200; // 2 hours in seconds
    sessionActive = true;
    document.getElementById('dashboard').style.display = 'none';
    document.getElementById('examContainer').style.display = 'block';
    document.getElementById('modeTitle').textContent = 'Exam Mode';
    document.getElementById('trainingFeedback').style.display = 'none';
    initializeExam();
}

function setTrainingTime() {
    const minutes = parseInt(document.getElementById('timeLimit').value, 10) || 60;
    if (minutes < 1) {
        alert('Please enter a time of at least 1 minute');
        return;
    }
    selectedTrainingTime = minutes;
    isTimeSet = true;
    isUnlimitedTime = false;
}

function setUnlimitedTime() {
    selectedTrainingTime = 999999; // Very high number for "unlimited"
    isTimeSet = true;
    isUnlimitedTime = true;
}

function beginTraining() {
    if (!isTimeSet) {
        alert('Please set a time limit first');
        return;
    }

    isTrainingMode = true;
    isUnlimitedTime = (selectedTrainingTime === 999999);
    sessionActive = true;
    timeLeft = selectedTrainingTime * 60;

    document.getElementById('dashboard').style.display = 'none';
    document.getElementById('examContainer').style.display = 'block';
    document.getElementById('modeTitle').textContent = 'Training Mode';
    document.getElementById('trainingFeedback').style.display = 'none';

    initializeExam();
}

function startTrainingMode(unlimited) {
    isTrainingMode = true;
    isUnlimitedTime = unlimited;
    sessionActive = true;
    
    if (unlimited) {
        timeLeft = 999999; // Very high number for "unlimited"
    } else {
        const minutes = parseInt(document.getElementById('timeLimit').value) || 60;
        timeLeft = minutes * 60;
    }
    
    document.getElementById('dashboard').style.display = 'none';
    document.getElementById('examContainer').style.display = 'block';
    document.getElementById('modeTitle').textContent = 'Training Mode';
    initializeExam();
}

function continueSession() {
    // Resume from saved session
    const savedData = JSON.parse(localStorage.getItem('examSessionData') || '{}');
    if (savedData && savedData.sessionActive) {
        currentQuestion = savedData.currentQuestion || 0;
        userAnswers = savedData.userAnswers || {};
        timeLeft = savedData.timeLeft || 3600;
        isTrainingMode = savedData.isTrainingMode || false;
        isUnlimitedTime = savedData.isUnlimitedTime || false;
        sessionActive = true;
        document.getElementById('dashboard').style.display = 'none';
        document.getElementById('examContainer').style.display = 'block';
        document.getElementById('modeTitle').textContent = isTrainingMode ? 'Training Mode' : 'Exam Mode';
        document.getElementById('trainingFeedback').style.display = 'none';
        initializeExam();
    }
}

function resetSession() {
    clearInterval(timerInterval);
    clearStorage();
    currentQuestion = 0;
    userAnswers = {};
    timeLeft = 3600;
    sessionActive = false;
    document.getElementById('continueButton').style.display = 'none';
    const incompleteNotice = document.getElementById('incompleteSessionNotice');
    if (incompleteNotice) incompleteNotice.style.display = 'none';
    clearModeSelection();
    alert('Session has been reset');
}

function backToDashboard() {
    saveToStorage();
    document.getElementById('dashboard').style.display = 'block';
    document.getElementById('examContainer').style.display = 'none';
    document.getElementById('results').style.display = 'none';
    document.getElementById('examContent').style.display = 'block';
    clearModeSelection();
    // Reflect any stats changes that happened during the session.
    try { renderQuestionSets(); } catch (_) { /* render is optional */ }
}

// Initialize the exam screen.
// IMPORTANT: do NOT re-read examSessionData here. Both callers already set
// the relevant state themselves:
//   - startExamMode / beginTraining set isTrainingMode + sessionActive fresh
//   - continueSession restores isTrainingMode + the rest from storage explicitly
// Re-reading storage in this function used to clobber a freshly-set
// isTrainingMode=true with a stale `false` left over from a previous Exam
// session, which broke training-mode feedback on every fresh Training start
// until the user manually clicked Reset Session.
function initializeExam() {
    // Initialize userAnswers for any questions that don't have an entry yet.
    if (typeof questions !== 'undefined') {
        questions.forEach((question, index) => {
            if (!userAnswers[index]) {
                userAnswers[index] = question.maxSelections > 1 ? [] : [];
            }
        });
    }
    
    if (document.getElementById('continueButton')) {
        document.getElementById('continueButton').style.display = sessionActive ? 'block' : 'none';
    }
    
    displayQuestion();
    startTimer();
    updateProgress();
}

// Modified displayQuestion to show feedback in training mode
function displayQuestion() {
    if (typeof questions === 'undefined' || !questions[currentQuestion]) return;
    
    const question = questions[currentQuestion];
    const maxSelections = question.maxSelections || 1;
    
    document.getElementById('questionNumber').textContent = `Question ${currentQuestion + 1} of ${questions.length}`;
    
    // Add instruction about multiple selections
    let instructionText = question.text;
    if (maxSelections > 1) {
        instructionText += `\n\n(Select ${maxSelections} answers)`;
    }
    document.getElementById('questionText').innerText = instructionText;
    
    const choicesContainer = document.getElementById('choices');
    choicesContainer.innerHTML = '';
    
    Object.entries(question.choices).forEach(([key, value]) => {
        const choiceDiv = document.createElement('div');
        choiceDiv.className = 'choice';
        choiceDiv.dataset.choiceKey = key;
        choiceDiv.onclick = () => selectAnswer(key);

        choiceDiv.innerHTML = `
            <div class="choice-label">${key}</div>
            <div class="choice-content">${value}</div>
        `;
        choicesContainer.appendChild(choiceDiv);
    });

    // Paint .selected from the data, not from the click event — keeps the
    // visual state in lockstep with userAnswers across re-renders.
    refreshChoiceSelection();

    // Training mode: also paint per-option correct/incorrect feedback so the
    // right answer is visible on the option card itself, immediately, with no
    // dashboard or reset-session detour. This is the missing refresh step.
    if (isTrainingMode && userAnswers[currentQuestion] && userAnswers[currentQuestion].length > 0) {
        applyTrainingFeedback();
        showQuestionFeedback();
    } else if (isTrainingMode && document.getElementById('trainingFeedback')) {
        document.getElementById('trainingFeedback').style.display = 'none';
    }

    updateNavigationButtons();
}

// Repaint .selected on every choice card from userAnswers. No reliance on the
// click event target — so navigation, re-renders, and programmatic changes all
// stay in sync with the underlying data.
function refreshChoiceSelection() {
    const choicesContainer = document.getElementById('choices');
    if (!choicesContainer) return;
    const userAnswer = userAnswers[currentQuestion] || [];
    const userSet = new Set(Array.isArray(userAnswer) ? userAnswer : [userAnswer]);
    choicesContainer.querySelectorAll('.choice').forEach((el) => {
        const key = el.dataset.choiceKey;
        el.classList.toggle('selected', userSet.has(key));
    });
}

// Training-mode per-option highlight: green check on correct answers, red X on
// the user's incorrect picks. Called after every answer change and after every
// re-render so the right option is visible on the card itself the moment it's
// known — not buried in a text line below.
function applyTrainingFeedback() {
    const choicesContainer = document.getElementById('choices');
    if (!choicesContainer) return;

    // Always clear stale state first.
    choicesContainer.querySelectorAll('.choice').forEach((el) => {
        el.classList.remove('choice--correct', 'choice--incorrect');
    });

    if (!isTrainingMode) return;
    const question = questions && questions[currentQuestion];
    if (!question) return;
    const userAnswer = userAnswers[currentQuestion] || [];
    if (!userAnswer.length) return;

    const correctRaw = question.answer;
    const correctSet = new Set(Array.isArray(correctRaw) ? correctRaw : [correctRaw]);
    const userSet = new Set(userAnswer);

    choicesContainer.querySelectorAll('.choice').forEach((el) => {
        const key = el.dataset.choiceKey;
        if (correctSet.has(key)) {
            el.classList.add('choice--correct');
        } else if (userSet.has(key)) {
            el.classList.add('choice--incorrect');
        }
    });
}

function selectAnswer(choice) {
    if (typeof questions === 'undefined' || !questions[currentQuestion]) return;

    const question = questions[currentQuestion];
    const maxSelections = question.maxSelections || 1;

    if (!userAnswers[currentQuestion]) {
        userAnswers[currentQuestion] = [];
    }

    const currentAnswers = userAnswers[currentQuestion];
    const choiceIndex = currentAnswers.indexOf(choice);

    if (choiceIndex > -1) {
        // Toggle off
        currentAnswers.splice(choiceIndex, 1);
    } else if (currentAnswers.length < maxSelections) {
        currentAnswers.push(choice);
    } else {
        alert(`You can only select ${maxSelections} answers.`);
        return;
    }

    // Single source of truth: rebuild the visual state from userAnswers.
    refreshChoiceSelection();

    if (isTrainingMode) {
        // Immediately recompute and paint the correct/incorrect option styling.
        // This is the fix: previously only the text below was updated; the
        // option cards never got a result class, so the correct answer was
        // never visually highlighted on the card itself.
        applyTrainingFeedback();
        showQuestionFeedback();
    }

    saveToStorage();
}

// New function to show feedback for current question (training mode)
function showQuestionFeedback() {
    if (!isTrainingMode || !document.getElementById('trainingFeedback')) return;
    
    const question = questions[currentQuestion];
    const feedbackDiv = document.getElementById('trainingFeedback');
    const userAnswer = userAnswers[currentQuestion] || [];
    const correctAnswer = question.answer;
    
    let isCorrect;
    if (Array.isArray(correctAnswer)) {
        const sortedUser = [...userAnswer].sort();
        const sortedCorrect = [...correctAnswer].sort();
        isCorrect = JSON.stringify(sortedUser) === JSON.stringify(sortedCorrect);
    } else {
        isCorrect = userAnswer[0] === correctAnswer;
    }
    
    feedbackDiv.innerHTML = `
        <div style="margin-bottom: 10px; color: ${isCorrect ? '#28a745' : '#dc3545'}; font-weight: bold;">
            ${isCorrect ? '✓ Correct!' : '✗ Incorrect'}
        </div>
        <div>Your answer: ${userAnswer.length > 0 ? userAnswer.join(', ') : 'Not answered'}</div>
        <div>Correct answer: ${Array.isArray(correctAnswer) ? correctAnswer.join(', ') : correctAnswer}</div>
    `;
    feedbackDiv.style.display = 'block';
}

function nextQuestion() {
    if (typeof questions !== 'undefined' && currentQuestion < questions.length - 1) {
        currentQuestion++;
        displayQuestion();
        updateProgress();
    }
}

function previousQuestion() {
    if (currentQuestion > 0) {
        currentQuestion--;
        displayQuestion();
        updateProgress();
    }
}

function updateNavigationButtons() {
    const prevButton = document.getElementById('prevButton');
    const nextButton = document.getElementById('nextButton');
    const submitButton = document.getElementById('submitButton');
    
    if (prevButton) prevButton.disabled = currentQuestion === 0;
    if (nextButton) nextButton.style.display = (typeof questions !== 'undefined' && currentQuestion === questions.length - 1) ? 'none' : 'inline-block';
    if (submitButton) submitButton.style.display = (typeof questions !== 'undefined' && currentQuestion === questions.length - 1) ? 'inline-block' : 'none';
}

function updateProgress() {
    if (typeof questions === 'undefined') return;
    
    const progress = Math.round(((currentQuestion + 1) / questions.length) * 100);
    const progressBar = document.getElementById('progressBar');
    if (progressBar) {
        progressBar.style.width = `${progress}%`;
    }
}

function startTimer() {
    if (timerInterval) clearInterval(timerInterval);
    
    timerInterval = setInterval(() => {
        if (!isUnlimitedTime) {
            timeLeft--;
            updateTimerDisplay();
            
            if (timeLeft <= 0) {
                clearInterval(timerInterval);
                submitExam();
            }
        } else {
            updateTimerDisplay();
        }
    }, 1000);
}

function updateTimerDisplay() {
    const timerElement = document.getElementById('timer');
    if (!timerElement) return;
    
    if (isUnlimitedTime) {
        timerElement.textContent = 'Unlimited';
        timerElement.style.color = '';
        return;
    }
    
    const minutes = Math.floor(timeLeft / 60);
    const seconds = timeLeft % 60;
    const timerDisplay = `${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}`;
    timerElement.textContent = timerDisplay;
    
    // Change color when time is running low
    if (timeLeft <= 300) { // 5 minutes
        timerElement.style.color = '#ff4444';
    } else if (timeLeft <= 600) { // 10 minutes
        timerElement.style.color = '#ff8800';
    } else {
        timerElement.style.color = '';
    }
}

// Modified submitExam to handle training mode feedback
function submitExam() {
    clearInterval(timerInterval);
    calculateScore();

    // Save session result to history
    const correct = typeof lastScoreCorrectCount !== 'undefined' ? lastScoreCorrectCount : 0;
    const total = typeof questions !== 'undefined' ? questions.length : 0;
    const percentage = total ? Math.round((correct / total) * 100) : 0;
    const mode = isTrainingMode ? 'Training' : 'Exam';
    const now = new Date();
    const dateStr = now.toLocaleString();
    saveSessionHistory({
        mode: mode,
        score: percentage,
        correct: correct,
        total: total,
        date: dateStr
    });

    // Roll the per-set stats forward so the Question sets card shows progress.
    try {
        const activeSetId = QSetStore.getActiveId();
        if (activeSetId) QSetStore.updateStats(activeSetId, percentage);
    } catch (_) { /* localStorage may be disabled */ }

    if (isTrainingMode) {
        showFullscreenFeedback();
    } else {
        showResults();
    }

    sessionActive = false;
    saveToStorage();
    renderSessionHistory();
}

function calculateScore() {
    if (typeof questions === 'undefined') return;

    let correctCount = 0;
    const totalQuestions = questions.length;

    questions.forEach((question, index) => {
        const userAnswer = userAnswers[index] || [];
        const correctAnswer = question.answer;

        // Compare arrays for multiple choice questions
        if (Array.isArray(correctAnswer)) {
            const sortedUserAnswer = [...userAnswer].sort();
            const sortedCorrectAnswer = [...correctAnswer].sort();

            if (JSON.stringify(sortedUserAnswer) === JSON.stringify(sortedCorrectAnswer)) {
                correctCount++;
            }
        } else {
            if (userAnswer[0] === correctAnswer) {
                correctCount++;
            }
        }
    });

    lastScoreCorrectCount = correctCount;

    const percentage = Math.round((correctCount / totalQuestions) * 100);
    const incorrectCount = totalQuestions - correctCount;
    
    // Update score display
    const correctCountEl = document.getElementById('correctCount');
    const incorrectCountEl = document.getElementById('incorrectCount');
    const finalScoreEl = document.getElementById('finalScore');
    const scorePercentageEl = document.getElementById('scorePercentage');
    
    if (correctCountEl) correctCountEl.textContent = correctCount;
    if (incorrectCountEl) incorrectCountEl.textContent = incorrectCount;
    if (finalScoreEl) finalScoreEl.textContent = `${percentage}%`;
    if (scorePercentageEl) {
        scorePercentageEl.innerHTML = `
            <div style="font-size: 4rem; font-weight: bold; color: ${percentage >= 70 ? '#4CAF50' : '#f44336'}">
                ${percentage}%
            </div>
            <div style="font-size: 1.2rem; margin-top: 10px;">
                ${percentage >= 70 ? 'Congratulations! You passed!' : 'Better luck next time!'}
            </div>
        `;
    }
    
    generateQuestionReview();
}

function generateQuestionReview() {
    const reviewContainer = document.getElementById('questionReview');
    if (!reviewContainer || typeof questions === 'undefined') return;
    
    reviewContainer.innerHTML = '<h3>Question Review</h3>';
    
    questions.forEach((question, index) => {
        const userAnswer = userAnswers[index] || [];
        const correctAnswer = question.answer;
        
        // Determine if answer is correct
        let isCorrect = false;
        if (Array.isArray(correctAnswer)) {
            const sortedUserAnswer = [...userAnswer].sort();
            const sortedCorrectAnswer = [...correctAnswer].sort();
            isCorrect = JSON.stringify(sortedUserAnswer) === JSON.stringify(sortedCorrectAnswer);
        } else {
            isCorrect = userAnswer[0] === correctAnswer;
        }
        
        // Format answers for display
        const userAnswerDisplay = Array.isArray(userAnswer) && userAnswer.length > 0 
            ? userAnswer.join(', ') 
            : 'Not answered';
        
        const correctAnswerDisplay = Array.isArray(correctAnswer) 
            ? correctAnswer.join(', ') 
            : correctAnswer;
        
        const reviewItem = document.createElement('div');
        reviewItem.className = `review-item ${isCorrect ? 'correct' : 'incorrect'}`;
        reviewItem.innerHTML = `
            <div class="review-question">
                <strong>Question ${index + 1}:</strong> ${question.text.substring(0, 100)}...
            </div>
            <div class="review-answer">
                <span class="answer-label">Your Answer:</span> 
                <span class="answer-value">${userAnswerDisplay}</span>
            </div>
            <div class="review-correct">
                <span class="answer-label">Correct Answer:</span> 
                <span class="answer-value">${correctAnswerDisplay}</span>
            </div>
            <div class="review-status ${isCorrect ? 'status-correct' : 'status-incorrect'}">
                ${isCorrect ? '✓ Correct' : '✗ Incorrect'}
            </div>
        `;
        
        reviewContainer.appendChild(reviewItem);
    });
}

// New function for fullscreen training feedback
function showFullscreenFeedback() {
    const feedbackContent = document.getElementById('feedbackContent');
    if (!feedbackContent || typeof questions === 'undefined') return;
    
    feedbackContent.innerHTML = '';
    
    questions.forEach((question, index) => {
        const userAnswer = userAnswers[index] || [];
        const correctAnswer = question.answer;
        
        let isCorrect;
        if (Array.isArray(correctAnswer)) {
            const sortedUser = [...userAnswer].sort();
            const sortedCorrect = [...correctAnswer].sort();
            isCorrect = JSON.stringify(sortedUser) === JSON.stringify(sortedCorrect);
        } else {
            isCorrect = userAnswer[0] === correctAnswer;
        }
        
        const questionDiv = document.createElement('div');
        questionDiv.style.marginBottom = '20px';
        questionDiv.style.padding = '15px';
        questionDiv.style.borderLeft = `4px solid ${isCorrect ? '#28a745' : '#dc3545'}`;
        questionDiv.style.backgroundColor = '#f8f9fa';
        
        questionDiv.innerHTML = `
            <h3 style="margin-top: 0;">Question ${index + 1}</h3>
            <p><strong>Question:</strong> ${question.text}</p>
            <p style="color: ${isCorrect ? '#28a745' : '#dc3545'}">
                <strong>${isCorrect ? '✓ Correct' : '✗ Incorrect'}</strong>
            </p>
            <p><strong>Your answer:</strong> ${userAnswer.length > 0 ? userAnswer.join(', ') : 'Not answered'}</p>
            <p><strong>Correct answer:</strong> ${Array.isArray(correctAnswer) ? correctAnswer.join(', ') : correctAnswer}</p>
        `;
        
        feedbackContent.appendChild(questionDiv);
    });
    
    const fullscreenFeedback = document.getElementById('fullscreenFeedback');
    if (fullscreenFeedback) {
        fullscreenFeedback.style.display = 'block';
    }
}

function closeFeedback() {
    const fullscreenFeedback = document.getElementById('fullscreenFeedback');
    if (fullscreenFeedback) {
        fullscreenFeedback.style.display = 'none';
    }
    backToDashboard();
}

function showResults() {
    const examContent = document.getElementById('examContent');
    const results = document.getElementById('results');
    
    if (examContent) examContent.style.display = 'none';
    if (results) results.style.display = 'block';
}

function restartExam() {
    // Reset all variables
    currentQuestion = 0;
    userAnswers = {};
    timeLeft = 3600;
    isTrainingMode = false;
    isUnlimitedTime = false;
    sessionActive = false;
    
    // Clear timer
    if (timerInterval) {
        clearInterval(timerInterval);
    }
    
    // Reset timer display
    const timerElement = document.getElementById('timer');
    if (timerElement) {
        timerElement.textContent = '60:00';
        timerElement.style.color = '';
    }
    
    // Hide results and show exam content
    const results = document.getElementById('results');
    const examContent = document.getElementById('examContent');
    
    if (results) results.style.display = 'none';
    if (examContent) examContent.style.display = 'block';
    
    // Clear storage and reinitialize
    clearStorage();
    initializeExam();
}

// --- Session History (now PostgreSQL-backed, per signed-in user) ---
//
// Same synchronous API as before; we keep an in-memory cache hydrated from
// /api/history on sign-in and fire-and-forget writes to /api/history when
// the user finishes a session.
let historyCache = [];

async function bootstrapSessionHistory() {
    try {
        const r = await _authFetch('/api/history');
        if (r.ok && r.data && Array.isArray(r.data.history)) {
            historyCache = r.data.history.map(h => ({
                mode: h.mode,
                score: h.score,
                correct: h.correct,
                total: h.total,
                date: h.date ? new Date(h.date).toLocaleString() : '',
                setId: h.setId,
            }));
        } else {
            historyCache = [];
        }
    } catch (e) {
        console.warn('[history] bootstrap failed:', e);
        historyCache = [];
    }
}

function saveSessionHistory(result) {
    // Optimistic local push so renderSessionHistory paints immediately.
    historyCache.unshift(result);
    _authFetch('/api/history', {
        method: 'POST',
        body: JSON.stringify({
            mode: result.mode,
            score: result.score,
            correct: result.correct,
            total: result.total,
            setId: QSetStore.getActiveId() || null,
        }),
    }).catch((e) => console.warn('[history] append failed:', e));
}

function renderSessionHistory() {
    const historyList = document.getElementById('historyList');
    if (!historyList) return;

    if (!historyCache.length) {
        historyList.innerHTML = '<div style="color:#888;">No session history yet.</div>';
    } else {
        historyList.innerHTML = historyCache.map((h) => `
            <div style="padding:8px 0; border-bottom:1px solid #eee;">
                <strong>${h.mode}</strong> | Score: <b>${h.score}%</b> | Correct: ${h.correct}/${h.total} | Date: ${h.date}
            </div>
        `).join('');
    }

    // Incomplete session notice — still per-device via localStorage.
    const incompleteNotice = document.getElementById('incompleteSessionNotice');
    const sessionData = JSON.parse(localStorage.getItem('examSessionData') || '{}');
    if (incompleteNotice) {
        if (sessionData && sessionData.sessionActive) {
            incompleteNotice.style.display = 'block';
            const continueBtn = document.getElementById('continueButton');
            if (continueBtn) continueBtn.style.display = 'block';
        } else {
            incompleteNotice.style.display = 'none';
            const continueBtn = document.getElementById('continueButton');
            if (continueBtn) continueBtn.style.display = 'none';
        }
    }
}

function clearSessionHistory() {
    historyCache = [];
    _authFetch('/api/history', { method: 'DELETE' })
        .catch((e) => console.warn('[history] clear failed:', e));
    renderSessionHistory();
}

// --- Hook into exam/training completion ---

function submitExam() {
    clearInterval(timerInterval);
    calculateScore();

    // Save session result to history
    const correct = typeof lastScoreCorrectCount !== 'undefined' ? lastScoreCorrectCount : 0;
    const total = typeof questions !== 'undefined' ? questions.length : 0;
    const percentage = total ? Math.round((correct / total) * 100) : 0;
    const mode = isTrainingMode ? 'Training' : 'Exam';
    const now = new Date();
    const dateStr = now.toLocaleString();
    saveSessionHistory({
        mode: mode,
        score: percentage,
        correct: correct,
        total: total,
        date: dateStr
    });

    // Roll the per-set stats forward so the Question sets card shows progress.
    try {
        const activeSetId = QSetStore.getActiveId();
        if (activeSetId) QSetStore.updateStats(activeSetId, percentage);
    } catch (_) { /* localStorage may be disabled */ }

    if (isTrainingMode) {
        showFullscreenFeedback();
    } else {
        showResults();
    }

    sessionActive = false;
    saveToStorage();
    renderSessionHistory();
}

// --- Track last score for history ---
let lastScoreCorrectCount = 0;

function calculateScore() {
    if (typeof questions === 'undefined') return;

    let correctCount = 0;
    const totalQuestions = questions.length;

    questions.forEach((question, index) => {
        const userAnswer = userAnswers[index] || [];
        const correctAnswer = question.answer;

        // Compare arrays for multiple choice questions
        if (Array.isArray(correctAnswer)) {
            const sortedUserAnswer = [...userAnswer].sort();
            const sortedCorrectAnswer = [...correctAnswer].sort();

            if (JSON.stringify(sortedUserAnswer) === JSON.stringify(sortedCorrectAnswer)) {
                correctCount++;
            }
        } else {
            if (userAnswer[0] === correctAnswer) {
                correctCount++;
            }
        }
    });

    lastScoreCorrectCount = correctCount;

    const percentage = Math.round((correctCount / totalQuestions) * 100);
    const incorrectCount = totalQuestions - correctCount;
    
    // Update score display
    const correctCountEl = document.getElementById('correctCount');
    const incorrectCountEl = document.getElementById('incorrectCount');
    const finalScoreEl = document.getElementById('finalScore');
    const scorePercentageEl = document.getElementById('scorePercentage');
    
    if (correctCountEl) correctCountEl.textContent = correctCount;
    if (incorrectCountEl) incorrectCountEl.textContent = incorrectCount;
    if (finalScoreEl) finalScoreEl.textContent = `${percentage}%`;
    if (scorePercentageEl) {
        scorePercentageEl.innerHTML = `
            <div style="font-size: 4rem; font-weight: bold; color: ${percentage >= 70 ? '#4CAF50' : '#f44336'}">
                ${percentage}%
            </div>
            <div style="font-size: 1.2rem; margin-top: 10px;">
                ${percentage >= 70 ? 'Congratulations! You passed!' : 'Better luck next time!'}
            </div>
        `;
    }
    
    generateQuestionReview();
}

function generateQuestionReview() {
    const reviewContainer = document.getElementById('questionReview');
    if (!reviewContainer || typeof questions === 'undefined') return;
    
    reviewContainer.innerHTML = '<h3>Question Review</h3>';
    
    questions.forEach((question, index) => {
        const userAnswer = userAnswers[index] || [];
        const correctAnswer = question.answer;
        
        // Determine if answer is correct
        let isCorrect = false;
        if (Array.isArray(correctAnswer)) {
            const sortedUserAnswer = [...userAnswer].sort();
            const sortedCorrectAnswer = [...correctAnswer].sort();
            isCorrect = JSON.stringify(sortedUserAnswer) === JSON.stringify(sortedCorrectAnswer);
        } else {
            isCorrect = userAnswer[0] === correctAnswer;
        }
        
        // Format answers for display
        const userAnswerDisplay = Array.isArray(userAnswer) && userAnswer.length > 0 
            ? userAnswer.join(', ') 
            : 'Not answered';
        
        const correctAnswerDisplay = Array.isArray(correctAnswer) 
            ? correctAnswer.join(', ') 
            : correctAnswer;
        
        const reviewItem = document.createElement('div');
        reviewItem.className = `review-item ${isCorrect ? 'correct' : 'incorrect'}`;
        reviewItem.innerHTML = `
            <div class="review-question">
                <strong>Question ${index + 1}:</strong> ${question.text.substring(0, 100)}...
            </div>
            <div class="review-answer">
                <span class="answer-label">Your Answer:</span> 
                <span class="answer-value">${userAnswerDisplay}</span>
            </div>
            <div class="review-correct">
                <span class="answer-label">Correct Answer:</span> 
                <span class="answer-value">${correctAnswerDisplay}</span>
            </div>
            <div class="review-status ${isCorrect ? 'status-correct' : 'status-incorrect'}">
                ${isCorrect ? '✓ Correct' : '✗ Incorrect'}
            </div>
        `;
        
        reviewContainer.appendChild(reviewItem);
    });
}

// New function for fullscreen training feedback
function showFullscreenFeedback() {
    const feedbackContent = document.getElementById('feedbackContent');
    if (!feedbackContent || typeof questions === 'undefined') return;
    
    feedbackContent.innerHTML = '';
    
    questions.forEach((question, index) => {
        const userAnswer = userAnswers[index] || [];
        const correctAnswer = question.answer;
        
        let isCorrect;
        if (Array.isArray(correctAnswer)) {
            const sortedUser = [...userAnswer].sort();
            const sortedCorrect = [...correctAnswer].sort();
            isCorrect = JSON.stringify(sortedUser) === JSON.stringify(sortedCorrect);
        } else {
            isCorrect = userAnswer[0] === correctAnswer;
        }
        
        const questionDiv = document.createElement('div');
        questionDiv.style.marginBottom = '20px';
        questionDiv.style.padding = '15px';
        questionDiv.style.borderLeft = `4px solid ${isCorrect ? '#28a745' : '#dc3545'}`;
        questionDiv.style.backgroundColor = '#f8f9fa';
        
        questionDiv.innerHTML = `
            <h3 style="margin-top: 0;">Question ${index + 1}</h3>
            <p><strong>Question:</strong> ${question.text}</p>
            <p style="color: ${isCorrect ? '#28a745' : '#dc3545'}">
                <strong>${isCorrect ? '✓ Correct' : '✗ Incorrect'}</strong>
            </p>
            <p><strong>Your answer:</strong> ${userAnswer.length > 0 ? userAnswer.join(', ') : 'Not answered'}</p>
            <p><strong>Correct answer:</strong> ${Array.isArray(correctAnswer) ? correctAnswer.join(', ') : correctAnswer}</p>
        `;
        
        feedbackContent.appendChild(questionDiv);
    });
    
    const fullscreenFeedback = document.getElementById('fullscreenFeedback');
    if (fullscreenFeedback) {
        fullscreenFeedback.style.display = 'block';
    }
}

function closeFeedback() {
    const fullscreenFeedback = document.getElementById('fullscreenFeedback');
    if (fullscreenFeedback) {
        fullscreenFeedback.style.display = 'none';
    }
    backToDashboard();
}

function showResults() {
    const examContent = document.getElementById('examContent');
    const results = document.getElementById('results');
    
    if (examContent) examContent.style.display = 'none';
    if (results) results.style.display = 'block';
}

function restartExam() {
    // Reset all variables
    currentQuestion = 0;
    userAnswers = {};
    timeLeft = 3600;
    isTrainingMode = false;
    isUnlimitedTime = false;
    sessionActive = false;
    
    // Clear timer
    if (timerInterval) {
        clearInterval(timerInterval);
    }
    
    // Reset timer display
    const timerElement = document.getElementById('timer');
    if (timerElement) {
        timerElement.textContent = '60:00';
        timerElement.style.color = '';
    }
    
    // Hide results and show exam content
    const results = document.getElementById('results');
    const examContent = document.getElementById('examContent');
    
    if (results) results.style.display = 'none';
    if (examContent) examContent.style.display = 'block';
    
    // Clear storage and reinitialize
    clearStorage();
    initializeExam();
}

// Modified saveToStorage to include mode information
function saveToStorage() {
    const examData = {
        currentQuestion: currentQuestion,
        userAnswers: userAnswers,
        timeLeft: timeLeft,
        isTrainingMode: isTrainingMode,
        isUnlimitedTime: isUnlimitedTime,
        sessionActive: sessionActive // <-- ensure this is true while in progress
    };
    localStorage.setItem('examSessionData', JSON.stringify(examData));
}

// Modified loadFromStorage to check for existing session
function loadFromStorage() {
    const savedData = localStorage.getItem('examSessionData');
    if (savedData) {
        try {
            const sessionData = JSON.parse(savedData);
            if (sessionData.sessionActive) {
                const continueButton = document.getElementById('continueButton');
                if (continueButton) {
                    continueButton.style.display = 'block';
                }
                // Show incomplete session notice
                const incompleteNotice = document.getElementById('incompleteSessionNotice');
                if (incompleteNotice) incompleteNotice.style.display = 'block';
            }
        } catch (e) {
            console.error('Error loading from storage:', e);
        }
    }
}

function clearStorage() {
    localStorage.removeItem('examSessionData');
    localStorage.removeItem('pythonExamData'); // Clean up old storage key
}

// Initialize on load
window.addEventListener('load', function() {
    loadFromStorage();
    const totalQuestionsEl = document.getElementById('totalQuestionsCount');
    if (totalQuestionsEl && typeof questions !== 'undefined') {
        totalQuestionsEl.textContent = questions.length;
    }
    renderSessionHistory();
});

// Save when leaving
window.addEventListener('beforeunload', saveToStorage);

// Handle visibility change (when user switches tabs)
document.addEventListener('visibilitychange', () => {
    if (document.hidden) {
        saveToStorage();
    } else {
        loadFromStorage();
    }
});

// ---------------------------------------------------------------------------
// PDF upload → /api/generate (server.py)
// ---------------------------------------------------------------------------
let selectedPdfFile = null;
let analysisData = null;
let selectedQuestionCount = null;

function setUploadStatus(message, kind) {
    const el = document.getElementById('uploadStatus');
    if (!el) return;
    if (!message) {
        el.style.display = 'none';
        el.textContent = '';
        el.className = 'upload-status';
        return;
    }
    el.textContent = message;
    el.className = 'upload-status ' + (kind || '');
    el.style.display = 'block';
}

function isPdfFile(file) {
    if (!file) return false;
    if (file.type === 'application/pdf') return true;
    return /\.pdf$/i.test(file.name || '');
}

function resetAnalysisState() {
    analysisData = null;
    selectedQuestionCount = null;
    const panel = document.getElementById('analysisPanel');
    const loading = document.getElementById('analysisLoading');
    const result = document.getElementById('analysisResult');
    const hint = document.getElementById('chipHint');
    if (panel) panel.style.display = 'none';
    if (loading) loading.style.display = 'flex';
    if (result) result.style.display = 'none';
    if (hint) hint.textContent = '';
    document.querySelectorAll('#countChips .chip').forEach((chip) => {
        chip.classList.remove('chip--selected', 'chip--warn', 'chip--disabled');
        chip.disabled = false;
        chip.setAttribute('aria-checked', 'false');
        chip.removeAttribute('title');
    });
    updateGenerateButton();
}

function updateGenerateButton() {
    const btn = document.getElementById('uploadPdfBtn');
    if (!btn) return;
    if (isGenerationLimitReached()) {
        btn.disabled = true;
        btn.title = 'You have used all monthly generations for your current plan.';
        return;
    }
    btn.disabled = !(selectedPdfFile && analysisData && selectedQuestionCount);
    if (!btn.disabled) btn.removeAttribute('title');
}

function renderChips(analysis) {
    document.querySelectorAll('#countChips .chip').forEach((chip) => {
        const value = parseInt(chip.dataset.count, 10);
        chip.classList.remove('chip--selected', 'chip--warn', 'chip--disabled');
        chip.disabled = false;
        chip.setAttribute('aria-checked', 'false');

        if (value > analysis.max) {
            chip.classList.add('chip--disabled');
            chip.disabled = true;
            chip.title = 'Above this PDF’s recommended ceiling of ' + analysis.max + '.';
        } else if (value > analysis.recommendedHigh) {
            chip.classList.add('chip--warn');
            chip.title = 'Slightly above the suggested sweet spot ('
                + analysis.recommendedLow + '–' + analysis.recommendedHigh + ') — quality may dip.';
        } else {
            chip.title = 'Within the recommended range.';
        }
    });
}

function selectChip(chip) {
    if (chip.disabled || chip.classList.contains('chip--disabled')) return;
    document.querySelectorAll('#countChips .chip').forEach((c) => {
        c.classList.remove('chip--selected');
        c.setAttribute('aria-checked', 'false');
    });
    chip.classList.add('chip--selected');
    chip.setAttribute('aria-checked', 'true');
    selectedQuestionCount = parseInt(chip.dataset.count, 10);

    const hint = document.getElementById('chipHint');
    if (hint && analysisData) {
        if (selectedQuestionCount > analysisData.recommendedHigh) {
            hint.textContent = 'Heads up: this is above the suggested ceiling — some questions may feel thin.';
            hint.className = 'chip-hint chip-hint--warn';
        } else {
            hint.textContent = 'Good fit for this PDF.';
            hint.className = 'chip-hint chip-hint--ok';
        }
    }
    updateGenerateButton();
}

async function analyzePdf() {
    if (!selectedPdfFile) return;
    resetAnalysisState();

    const panel = document.getElementById('analysisPanel');
    const loading = document.getElementById('analysisLoading');
    const result = document.getElementById('analysisResult');
    if (panel) panel.style.display = 'block';

    const url = quizApiUrl('/api/analyze');
    const formData = new FormData();
    formData.append('pdf', selectedPdfFile);

    let response;
    try {
        response = await fetch(url, { method: 'POST', body: formData, credentials: 'include' });
    } catch (networkErr) {
        if (panel) panel.style.display = 'none';
        setUploadStatus(
            'Could not reach the backend at ' + url + '. Is server.py running? ('
            + networkErr.message + ')',
            'error'
        );
        return;
    }

    const bodyText = await response.text().catch(() => '');
    let data = null;
    try { data = bodyText ? JSON.parse(bodyText) : null; } catch (_) { /* non-JSON */ }

    if (!response.ok || !data || !data.ok) {
        if (panel) panel.style.display = 'none';
        const detail = (data && data.error) || (bodyText && bodyText.slice(0, 200)) || 'Analysis failed';
        setUploadStatus('Analysis failed: ' + detail, 'error');
        return;
    }

    analysisData = data;
    const msgEl = document.getElementById('analysisMessage');
    if (msgEl) msgEl.textContent = data.message;
    renderChips(data);

    if (loading) loading.style.display = 'none';
    if (result) result.style.display = 'block';
    updateGenerateButton();
}

function handlePdfSelection(file) {
    const nameEl = document.getElementById('selectedFileName');
    if (!file) {
        selectedPdfFile = null;
        if (nameEl) nameEl.textContent = '';
        resetAnalysisState();
        return;
    }
    if (!isPdfFile(file)) {
        selectedPdfFile = null;
        if (nameEl) nameEl.textContent = '';
        resetAnalysisState();
        setUploadStatus('Only PDF files are allowed.', 'error');
        return;
    }
    selectedPdfFile = file;
    if (nameEl) nameEl.textContent = 'Selected: ' + file.name;
    setUploadStatus('', '');
    resetAnalysisState();
    analyzePdf();
}

// ---------------------------------------------------------------------------
// Generation progress UI (driven by /api/generate/status polling)
// ---------------------------------------------------------------------------
const PHASE_LABELS = {
    queued:     'Queued',
    extracting: 'Reading PDF',
    chunking:   'Planning',
    generating: 'Generating',
    merging:    'Merging',
    writing:    'Saving',
    done:       'Done',
    error:      'Failed'
};

let progressElapsedTimer = null;
let progressStartedAt = 0;

function showGenerationProgress() {
    const panel = document.getElementById('generationProgress');
    const fill = document.getElementById('progressFill');
    const phase = document.getElementById('progressPhase');
    const elapsed = document.getElementById('progressElapsed');
    const msg = document.getElementById('progressMessage');
    if (!panel) return;
    panel.style.display = 'block';
    panel.classList.remove('gen-progress--done', 'gen-progress--error');
    if (fill) fill.style.width = '0%';
    if (phase) phase.textContent = 'Starting…';
    if (elapsed) elapsed.textContent = '0:00';
    if (msg) msg.textContent = 'Uploading PDF to the generator…';

    progressStartedAt = Date.now();
    if (progressElapsedTimer) clearInterval(progressElapsedTimer);
    progressElapsedTimer = setInterval(updateElapsedDisplay, 1000);
}

function updateElapsedDisplay() {
    const el = document.getElementById('progressElapsed');
    if (!el) return;
    const secs = Math.floor((Date.now() - progressStartedAt) / 1000);
    const m = Math.floor(secs / 60);
    const s = secs % 60;
    el.textContent = m + ':' + (s < 10 ? '0' : '') + s;
}

function stopElapsedTimer() {
    if (progressElapsedTimer) {
        clearInterval(progressElapsedTimer);
        progressElapsedTimer = null;
    }
}

function hideGenerationProgress() {
    stopElapsedTimer();
    const panel = document.getElementById('generationProgress');
    if (panel) panel.style.display = 'none';
}

function applyJobToProgress(job) {
    const fill = document.getElementById('progressFill');
    const phase = document.getElementById('progressPhase');
    const msg = document.getElementById('progressMessage');
    const panel = document.getElementById('generationProgress');
    if (fill) fill.style.width = Math.max(0, Math.min(100, job.percent || 0)) + '%';
    if (phase) phase.textContent = PHASE_LABELS[job.phase] || job.phase || '';
    if (msg) msg.textContent = job.message || '';
    if (panel) {
        panel.classList.toggle('gen-progress--done', job.state === 'done');
        panel.classList.toggle('gen-progress--error', job.state === 'error');
    }
}

async function pollGenerationStatus(jobId) {
    const statusUrl = quizApiUrl('/api/generate/status/' + encodeURIComponent(jobId));
    const POLL_INTERVAL_MS = 800;
    let consecutiveNetworkErrors = 0;

    while (true) {
        let response;
        try {
            response = await fetch(statusUrl, { method: 'GET', credentials: 'include' });
        } catch (networkErr) {
            consecutiveNetworkErrors += 1;
            if (consecutiveNetworkErrors >= 5) {
                throw new Error('Lost contact with server while polling: ' + networkErr.message);
            }
            await sleep(POLL_INTERVAL_MS);
            continue;
        }
        consecutiveNetworkErrors = 0;

        const data = await response.json().catch(() => null);
        if (!response.ok || !data || !data.ok || !data.job) {
            const detail = (data && data.error) || ('HTTP ' + response.status);
            throw new Error('Status check failed: ' + detail);
        }

        const job = data.job;
        applyJobToProgress(job);

        if (job.state === 'done') return job;
        if (job.state === 'error') {
            const err = new Error(job.error || 'Generation failed.');
            err.job = job;
            throw err;
        }
        await sleep(POLL_INTERVAL_MS);
    }
}

function sleep(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
}

async function uploadPdf() {
    if (isGenerationLimitReached()) {
        setUploadStatus(
            'You have used all your monthly generations. Upgrade your plan to continue.',
            'error'
        );
        return;
    }

    if (!selectedPdfFile) {
        setUploadStatus('Please choose a PDF first.', 'error');
        return;
    }
    if (!selectedQuestionCount) {
        setUploadStatus('Pick how many questions to generate.', 'error');
        return;
    }

    const btn = document.getElementById('uploadPdfBtn');
    if (btn) btn.disabled = true;
    setUploadStatus('', '');
    showGenerationProgress();

    // The server now persists the generated set directly into PostgreSQL
    // owned by the current user (see JobManager._persist_set), so the old
    // localStorage hand-off is no longer needed. Keep this as a no-op for
    // any older code paths that still call setPendingSave.
    try {
        QSetStore.setPendingSave({
            filename: selectedPdfFile.name,
            requestedCount: selectedQuestionCount,
            analysis: analysisData ? {
                pageCount: analysisData.pageCount,
                wordCount: analysisData.wordCount,
                recommendedLow: analysisData.recommendedLow,
                recommendedHigh: analysisData.recommendedHigh
            } : null,
            timestamp: Date.now()
        });
    } catch (_) { /* localStorage may be disabled */ }

    const formData = new FormData();
    formData.append('pdf', selectedPdfFile);
    formData.append('count', String(selectedQuestionCount));

    const url = quizApiUrl('/api/generate');
    let response;
    try {
        response = await fetch(url, { method: 'POST', body: formData, credentials: 'include' });
    } catch (networkErr) {
        hideGenerationProgress();
        setUploadStatus(
            'Could not reach the backend at ' + url + '. Is server.py running? '
            + '(' + networkErr.message + ')',
            'error'
        );
        if (btn) btn.disabled = false;
        return;
    }

    // Read body as text first so non-JSON error pages (e.g. Apache 405 HTML) still surface.
    const bodyText = await response.text().catch(() => '');
    let data = null;
    try { data = bodyText ? JSON.parse(bodyText) : null; } catch (_) { /* not JSON */ }

    if (!response.ok || !data || !data.ok || !data.jobId) {
        hideGenerationProgress();
        const statusPart = response.status + (response.statusText ? ' ' + response.statusText : '');
        let detail;
        if (data && data.error) {
            detail = data.error;
            if (data.usage && currentUser) {
                currentUser.usage = data.usage;
                if (data.usage.planTier) currentUser.planTier = data.usage.planTier;
                paintUserPill();
                updateGenerateButton();
            }
        } else {
            const snippet = (bodyText || '').replace(/\s+/g, ' ').trim().slice(0, 200);
            detail = snippet || 'No response body';
        }
        setUploadStatus('Failed to start: ' + url + ' returned ' + statusPart + ' — ' + detail, 'error');
        if (btn) btn.disabled = false;
        return;
    }

    // Job started — poll for status.
    try {
        const finalJob = await pollGenerationStatus(data.jobId);
        stopElapsedTimer();
        setUploadStatus(finalJob.message || 'Questions generated. Reloading…', 'success');
        try { localStorage.removeItem('examSessionData'); } catch (_) {}
        setTimeout(() => window.location.reload(), 1100);
    } catch (err) {
        stopElapsedTimer();
        setUploadStatus('Failed: ' + err.message, 'error');
        if (btn) btn.disabled = false;
    }
}


// ===========================================================================
// Saved-set integration: hydrate active set, finalize a just-generated set,
// render the UI list, and provide activate/delete helpers.
// ===========================================================================

function activeQuestionsArray() {
    return (typeof questions !== 'undefined' && Array.isArray(questions)) ? questions : null;
}

function replaceLoadedQuestions(newList) {
    // `questions` is declared as `const` in questions.js — we can't reassign,
    // but we can mutate the array contents in place, which is what all the
    // quiz code reads through.
    const target = activeQuestionsArray();
    if (!target || !Array.isArray(newList)) return false;
    target.length = 0;
    for (const q of newList) target.push(q);
    return true;
}

function applyActiveSetIfAny() {
    const id = QSetStore.getActiveId();
    if (!id) return;
    const record = QSetStore.get(id);
    if (!record || !Array.isArray(record.questions) || !record.questions.length) return;
    replaceLoadedQuestions(record.questions);
}

function tryFinalizePendingSave() {
    const pending = QSetStore.getPendingSave();
    if (!pending) return;
    const loaded = activeQuestionsArray();
    if (!loaded || !loaded.length) return;

    try {
        const filename = pending.filename || '';
        const title = filename
            ? filename.replace(/\.pdf$/i, '').replace(/[_-]+/g, ' ').trim() || filename
            : 'Generated set';

        // Deep-copy questions so subsequent in-memory mutations can't change the saved copy.
        const snapshot = loaded.map(q => ({
            number: q.number,
            text: q.text,
            choices: Object.assign({}, q.choices || {}),
            answer: Array.isArray(q.answer) ? q.answer.slice() : [q.answer],
            maxSelections: q.maxSelections || 1
        }));

        const analysis = pending.analysis || {};
        const record = QSetStore.save({
            title: title,
            ownerId: null,
            source: {
                type: 'pdf-generated',
                filename: filename || null,
                pageCount: analysis.pageCount || null,
                wordCount: analysis.wordCount || null,
                requestedCount: pending.requestedCount || null,
                producedCount: snapshot.length,
                generatorModel: pending.generatorModel || null,
                generatedAt: pending.timestamp ? new Date(pending.timestamp).toISOString() : null
            },
            questions: snapshot,
            stats: { sessionsRun: 0, lastPlayedAt: null, bestScore: null, averageScore: null }
        });
        if (record) QSetStore.setActiveId(record.id);
    } catch (e) {
        console.warn('[QSetStore] failed to finalize pending save:', e);
    } finally {
        QSetStore.clearPendingSave();
    }
}

function renderQuestionSets() {
    const listEl = document.getElementById('questionSetsList');
    if (!listEl) return;
    listEl.innerHTML = '';

    const sets = QSetStore.list();
    const activeId = QSetStore.getActiveId();

    if (!sets.length) {
        const p = document.createElement('p');
        p.className = 'qsets-empty';
        p.textContent = 'No saved sets yet. Generate a question set from a PDF and it will be saved here automatically.';
        listEl.appendChild(p);
        return;
    }

    for (const s of sets) {
        const isActive = s.id === activeId;
        const item = document.createElement('article');
        item.className = 'qset-item' + (isActive ? ' qset-item--active' : '');
        item.dataset.id = s.id;

        const main = document.createElement('div');
        main.className = 'qset-item__main';

        const title = document.createElement('h4');
        title.className = 'qset-item__title';
        title.textContent = s.title || 'Untitled set';

        const sub = document.createElement('p');
        sub.className = 'qset-item__sub';
        const parts = [(s.questionCount || 0) + ' questions'];
        if (s.createdAt) {
            try { parts.push(new Date(s.createdAt).toLocaleDateString()); } catch (_) {}
        }
        if (s.bestScore != null) parts.push('Best ' + s.bestScore + '%');
        sub.textContent = parts.join(' · ');

        main.appendChild(title);
        main.appendChild(sub);

        const actions = document.createElement('div');
        actions.className = 'qset-item__actions';

        if (isActive) {
            const badge = document.createElement('span');
            badge.className = 'qset-item__badge';
            badge.textContent = 'Active';
            actions.appendChild(badge);
        } else {
            const useBtn = document.createElement('button');
            useBtn.type = 'button';
            useBtn.className = 'btn btn--secondary btn--sm';
            useBtn.textContent = 'Use';
            useBtn.addEventListener('click', () => activateQuestionSet(s.id));
            actions.appendChild(useBtn);
        }

        const delBtn = document.createElement('button');
        delBtn.type = 'button';
        delBtn.className = 'btn btn--ghost-danger btn--sm';
        delBtn.textContent = 'Delete';
        delBtn.setAttribute('aria-label', 'Delete ' + (s.title || 'set'));
        delBtn.addEventListener('click', () => deleteQuestionSet(s.id));
        actions.appendChild(delBtn);

        item.appendChild(main);
        item.appendChild(actions);
        listEl.appendChild(item);
    }
}

function activateQuestionSet(id) {
    const record = QSetStore.get(id);
    if (!record) return;
    QSetStore.setActiveId(id);
    // The questions array we'll load is structurally different from any in-flight
    // session, so drop the in-progress state (history is preserved).
    try { localStorage.removeItem('examSessionData'); } catch (_) {}
    // Reload so questions.js loads cleanly and DOMContentLoaded re-hydrates from the new active set.
    window.location.reload();
}

function deleteQuestionSet(id) {
    const summaries = QSetStore.list();
    const summary = summaries.find(s => s.id === id);
    if (!summary) return;
    const ok = window.confirm('Delete "' + (summary.title || 'this set') + '"? This cannot be undone.');
    if (!ok) return;
    const wasActive = QSetStore.getActiveId() === id;
    QSetStore.delete(id);
    renderQuestionSets();
    if (wasActive) {
        // Drop the in-flight session and reload — the next active source becomes
        // whatever questions.js holds on disk (the last generation, or the demo bank).
        try { localStorage.removeItem('examSessionData'); } catch (_) {}
        window.location.reload();
    }
}


document.addEventListener('DOMContentLoaded', () => {
    // Auth-gate the dashboard. checkAuthOnLoad() either:
    //   • shows the sign-in overlay, OR
    //   • hides it, hydrates QSetStore from PostgreSQL for the signed-in user,
    //     swaps the active set into `questions`, and paints the sets list.
    checkAuthOnLoad().catch(e => {
        console.warn('[auth] checkAuthOnLoad failed:', e);
        showAuthOverlay();
    });

    const dropZone = document.getElementById('dropZone');
    const fileInput = document.getElementById('pdfFileInput');
    if (!dropZone || !fileInput) return;

    dropZone.addEventListener('click', () => fileInput.click());
    dropZone.addEventListener('keydown', (e) => {
        if (e.key === 'Enter' || e.key === ' ' || e.key === 'Spacebar') {
            e.preventDefault();
            fileInput.click();
        }
    });
    fileInput.addEventListener('change', (e) => {
        const file = e.target.files && e.target.files[0];
        handlePdfSelection(file);
    });

    document.querySelectorAll('#countChips .chip').forEach((chip) => {
        chip.addEventListener('click', () => selectChip(chip));
        chip.addEventListener('keydown', (e) => {
            if (e.key === 'Enter' || e.key === ' ' || e.key === 'Spacebar') {
                e.preventDefault();
                selectChip(chip);
            }
        });
    });

    ['dragenter', 'dragover'].forEach((evt) => {
        dropZone.addEventListener(evt, (e) => {
            e.preventDefault();
            e.stopPropagation();
            dropZone.classList.add('dragover');
        });
    });
    ['dragleave', 'dragend'].forEach((evt) => {
        dropZone.addEventListener(evt, (e) => {
            e.preventDefault();
            e.stopPropagation();
            dropZone.classList.remove('dragover');
        });
    });
    dropZone.addEventListener('drop', (e) => {
        e.preventDefault();
        e.stopPropagation();
        dropZone.classList.remove('dragover');
        const file = e.dataTransfer && e.dataTransfer.files && e.dataTransfer.files[0];
        handlePdfSelection(file);
    });

    // Prevent the browser from navigating to a dropped file if the user misses the zone.
    window.addEventListener('dragover', (e) => e.preventDefault());
    window.addEventListener('drop', (e) => e.preventDefault());
});
