// AUTO-GENERATED by backend.py. Rerun the script (or use the upload UI) to regenerate.
// Source: upload-l03xh_l_.pdf
// Sections processed: 2
// Requested: 20  Produced: 20
// Consumed by Cert.js as the global `questions` array.

const questions = [
  {
    number: 1,
    text: `According to Freud's theory, at what age do children become aware of genital differences?`,
    choices: {
      A: `1-2 years`,
      B: `2.5-3 years`,
      C: `4-5 years`,
      D: `6-7 years`
    },
    answer: ["B"],
    maxSelections: 1
  },
  {
    number: 2,
    text: `What is the primary focus of Social Learning Theory in gender development?`,
    choices: {
      A: `Biological determinism`,
      B: `Observation and imitation`,
      C: `Cognitive schemas`,
      D: `Psychosexual stages`
    },
    answer: ["B"],
    maxSelections: 1
  },
  {
    number: 3,
    text: `Which feminist critique directly challenges Freud's concept of "penis envy"?`,
    choices: {
      A: `It ignores cultural variability`,
      B: `It reinforces male superiority`,
      C: `It overemphasizes childhood trauma`,
      D: `It neglects hormonal influences`
    },
    answer: ["B"],
    maxSelections: 1
  },
  {
    number: 4,
    text: `In Kohlberg's Cognitive Developmental Theory, what marks the "Gender Constancy" stage?`,
    choices: {
      A: `Recognizing gender is constant across situations`,
      B: `Labeling gender based on appearance`,
      C: `Imitating same-sex parents`,
      D: `Experiencing Oedipal conflict`
    },
    answer: ["A"],
    maxSelections: 1
  },
  {
    number: 5,
    text: `Which anthropological practice exemplifies violence against women?`,
    choices: {
      A: `Bride price`,
      B: `Female genital mutilation`,
      C: `Dowry system`,
      D: `All of the above`
    },
    answer: ["D"],
    maxSelections: 1
  },
  {
    number: 6,
    text: `What does Parsons' Structural Functionalist Theory emphasize about gender roles?`,
    choices: {
      A: `They are biologically determined`,
      B: `They create complementary family units`,
      C: `They should be eliminated for equality`,
      D: `They vary randomly across cultures`
    },
    answer: ["B"],
    maxSelections: 1
  },
  {
    number: 7,
    text: `Which term describes the internalization of societal gender expectations?`,
    choices: {
      A: `Gender typing`,
      B: `Oedipal conflict`,
      C: `Penis envy`,
      D: `Electra complex`
    },
    answer: ["A"],
    maxSelections: 1
  },
  {
    number: 8,
    text: `What did Margaret Mead's cross-cultural research demonstrate about gender?`,
    choices: {
      A: `Universal male dominance`,
      B: `Fixed biological determinism`,
      C: `Variability in gender behaviors`,
      D: `Inevitability of patriarchy`
    },
    answer: ["C"],
    maxSelections: 1
  },
  {
    number: 9,
    text: `Which theory views gender as emerging through social interactions and symbols?`,
    choices: {
      A: `Psychoanalytic Theory`,
      B: `Symbolic Interactionism`,
      C: `Structural Functionalism`,
      D: `Biological Determinism`
    },
    answer: ["B"],
    maxSelections: 1
  },
  {
    number: 10,
    text: `What is a key criticism of Freud's psychoanalytic theory of gender?`,
    choices: {
      A: `It ignores cognitive development`,
      B: `It reinforces gender stereotypes`,
      C: `It lacks empirical evidence`,
      D: `All of the above`
    },
    answer: ["D"],
    maxSelections: 1
  },
  {
    number: 11,
    text: `According to Engels, what perpetuates women's oppression?`,
    choices: {
      A: `Biological differences`,
      B: `Class structure`,
      C: `Religious doctrines`,
      D: `Hormonal factors`
    },
    answer: ["B"],
    maxSelections: 1
  },
  {
    number: 12,
    text: `Which concept refers to the interplay of race, class, and gender in discrimination?`,
    choices: {
      A: `Gender typing`,
      B: `Intersectionality`,
      C: `Oedipal conflict`,
      D: `Socialization`
    },
    answer: ["B"],
    maxSelections: 1
  },
  {
    number: 13,
    text: `What does Symbolic Interactionism emphasize about gender development?`,
    choices: {
      A: `Biological predispositions`,
      B: `Learned meanings through interaction`,
      C: `Universal archetypes`,
      D: `Economic class struggles`
    },
    answer: ["B"],
    maxSelections: 1
  },
  {
    number: 14,
    text: `Which practice reflects son preference in some cultures?`,
    choices: {
      A: `Selective abortion of female fetuses`,
      B: `Early marriage of girls`,
      C: `Nutritional deprivation of girls`,
      D: `All of the above`
    },
    answer: ["D"],
    maxSelections: 1
  },
  {
    number: 15,
    text: `What is the primary focus of Cognitive Developmental Theory in gender?`,
    choices: {
      A: `Children actively construct gender understanding`,
      B: `Parents reinforce gender roles`,
      C: `Biological factors determine behavior`,
      D: `Society imposes rigid categories`
    },
    answer: ["A"],
    maxSelections: 1
  },
  {
    number: 16,
    text: `Which term describes societies prioritizing group goals over individual goals?`,
    choices: {
      A: `Individualism`,
      B: `Collectivism`,
      C: `Functionalism`,
      D: `Intersectionality`
    },
    answer: ["B"],
    maxSelections: 1
  },
  {
    number: 17,
    text: `What does Gender Schema Theory propose about children?`,
    choices: {
      A: `They passively absorb cultural norms`,
      B: `They actively organize information by gender`,
      C: `They resist gender categorization`,
      D: `They are biologically pre-programmed`
    },
    answer: ["B"],
    maxSelections: 1
  },
  {
    number: 18,
    text: `Which feminist perspective seeks to eliminate gender stratification entirely?`,
    choices: {
      A: `Liberal Feminism`,
      B: `Socialist Feminism`,
      C: `Radical Feminism`,
      D: `Cultural Feminism`
    },
    answer: ["C"],
    maxSelections: 1
  },
  {
    number: 19,
    text: `What anthropological evidence challenges biological determinism of gender?`,
    choices: {
      A: `Universal male dominance`,
      B: `Cross-cultural variability in gender roles`,
      C: `Fixed division of labor`,
      D: `Hormonal studies`
    },
    answer: ["B"],
    maxSelections: 1
  },
  {
    number: 20,
    text: `Which feminist theory advocates for the abolition of gender as a means to achieve equality?`,
    choices: {
      A: `Liberal Feminism`,
      B: `Socialist Feminism`,
      C: `Radical Feminism`,
      D: `Functionalist Theory`
    },
    answer: ["C"],
    maxSelections: 1
  }
];
